### ISSUE TITLE
[BUG] The bot not allowing any discord.com urls

### ISSUE THREAD

**Issue by pranavbaburaj** [TheophileDiot/Omnitron#66]
**Describe the bug**
The bot is supposed to prevent invitation url(s) to other servers. but seem to block all the url that starts with discord.com.

**To Reproduce**
Send a link that starts with discord.com and is not a server invite. like an emoji url

**Desktop (please complete the following information):**

- OS: Parrot OS [Linux]
- Discord version [e.g. Stable 101451 (b46c230)]

**Additional context**
I think the regex should be replace with something else 🤔 ?

**Comment by pranavbaburaj** [comment]
All good.

**Comment by TheophileDiot** [comment]
Fixed in #67 :D
